site_builder.lo: /back/code/php_code/php_module/php_module_demo/site_builder.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/back/code/php_code/php_module/php_module_demo $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /back/code/php_code/php_module/php_module_demo/site_builder.c -o site_builder.lo 
$(phplibdir)/site_builder.la: ./site_builder.la
	$(LIBTOOL) --mode=install cp ./site_builder.la $(phplibdir)

./site_builder.la: $(shared_objects_site_builder) $(SITE_BUILDER_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_site_builder) $(SITE_BUILDER_SHARED_LIBADD)

